/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/robot.glb -o src/components/3d/Robot.jsx 
Author: shonwall360 (https://sketchfab.com/shonwall360)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-alex-82fcab4a190f4663ab2717dc5f40e40e
Title: Robot A.L.E.X
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robot.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.14}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.pCube291_back_panel_0.geometry} material={materials.back_panel} />
          <mesh geometry={nodes.polySurface2685_damper3_0.geometry} material={materials.damper3} />
          <mesh geometry={nodes.polySurface2676_damper3_0.geometry} material={materials.damper3} />
          <mesh geometry={nodes.polySurface2573_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface2568_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface2564_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface2563_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface2562_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface2561_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface2549_wires_3_0.geometry} material={materials.wires_3} />
          <mesh geometry={nodes.polySurface2504_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface2450_front_vent_0.geometry} material={materials.front_vent} />
          <mesh geometry={nodes.polySurface2398_head_3_0.geometry} material={materials.head_3} />
          <mesh geometry={nodes.polySurface2396_head_4_0.geometry} material={materials.head_4} />
          <mesh geometry={nodes.polySurface2260_front_panel_0.geometry} material={materials.front_panel} />
          <mesh geometry={nodes.polySurface10368_camera_1_0.geometry} material={materials.camera_1} />
          <mesh geometry={nodes.polySurface10367_Camera_3_0.geometry} material={materials.Camera_3} />
          <mesh geometry={nodes.polySurface10367_camera_2_0.geometry} material={materials.camera_2} />
          <mesh geometry={nodes.polySurface10271_ant_2_0.geometry} material={materials.ant_2} />
          <mesh geometry={nodes.polySurface10268_ant_1_0.geometry} material={materials.ant_1} />
          <mesh geometry={nodes.polySurface10174_bottom3_0.geometry} material={materials.bottom3} />
          <mesh geometry={nodes.polySurface10173_buttom1_0.geometry} material={materials.buttom1} />
          <mesh geometry={nodes.polySurface10170_bottom2_0.geometry} material={materials.bottom2} />
          <mesh geometry={nodes.polySurface3436_backpack_2_0.geometry} material={materials.backpack_2} />
          <mesh geometry={nodes.polySurface2774_gophra_1_0.geometry} material={materials.gophra_1} />
          <mesh geometry={nodes.polySurface8651_arm_armor_0.geometry} material={materials.arm_armor} />
          <mesh geometry={nodes.polySurface10194_toparms_0.geometry} material={materials.toparms} />
          <mesh geometry={nodes.polySurface8694_arms2_0.geometry} material={materials.arms2} />
          <mesh geometry={nodes.polySurface9813_armor_0.geometry} material={materials.armor} />
          <mesh geometry={nodes.polySurface9932_back_vent_0.geometry} material={materials.back_vent} />
          <mesh geometry={nodes.polySurface9982_cillinders_3_0.geometry} material={materials.cillinders_3} />
          <mesh geometry={nodes.polySurface9984_front_armor_legpannels_0.geometry} material={materials.front_armor_legpannels} />
          <mesh geometry={nodes.polySurface9987_leg_cillinders2_0.geometry} material={materials.leg_cillinders2} />
          <mesh geometry={nodes.polySurface9992_armor_legs_arms_0.geometry} material={materials.armor_legs_arms} />
          <mesh geometry={nodes.polySurface10017_body_armor_0.geometry} material={materials.body_armor} />
          <mesh geometry={nodes.polySurface8795_leg_back_cillinders_0.geometry} material={materials.leg_back_cillinders} />
          <mesh geometry={nodes.polySurface9022_leg_cillinders_0.geometry} material={materials.leg_cillinders} />
          <mesh geometry={nodes.polySurface10026_detail_0.geometry} material={materials.detail} />
          <mesh geometry={nodes.polySurface10024_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface2710_damper2_0.geometry} material={materials.damper2} />
          <mesh geometry={nodes.polySurface2719_bolts_0.geometry} material={materials.bolts} />
          <mesh geometry={nodes.polySurface3419_head_0.geometry} material={materials.head} />
          <mesh geometry={nodes.polySurface2310_skulls_0.geometry} material={materials.skulls} />
          <mesh geometry={nodes.polySurface2402_filters_0.geometry} material={materials.filters} />
          <mesh geometry={nodes.polySurface10031_filters_2_0.geometry} material={materials.filters_2} />
          <mesh geometry={nodes.polySurface2503_back_cillinders_0.geometry} material={materials.back_cillinders} />
          <mesh geometry={nodes.polySurface2572_back_bolts_0.geometry} material={materials.back_bolts} />
          <mesh geometry={nodes.polySurface2613_backpack_0.geometry} material={materials.backpack} />
          <mesh geometry={nodes.polySurface10156_flat_damper_0.geometry} material={materials.flat_damper} />
          <mesh geometry={nodes.polySurface10158_legs_0.geometry} material={materials.legs} />
          <mesh geometry={nodes.polySurface10161_bottoms_0.geometry} material={materials.bottoms} />
          <mesh geometry={nodes.polySurface2360_pipe_0.geometry} material={materials.pipe} />
          <mesh geometry={nodes.polySurface10213_front_panel_2_0.geometry} material={materials.front_panel_2} />
          <mesh geometry={nodes.polySurface10176_arms_0.geometry} material={materials.arms} />
          <mesh geometry={nodes.polySurface10272_ANT__0.geometry} material={materials.material} />
          <mesh geometry={nodes.polySurface10270_dot_4_0.geometry} material={materials.dot_4} />
          <mesh geometry={nodes.polySurface2451_wires_0.geometry} material={materials.wires} />
          <mesh geometry={nodes.polySurface2548_wires_2_0.geometry} material={materials.wires_2} />
          <mesh geometry={nodes.polySurface10274_dot_3_0.geometry} material={materials.dot_3} />
          <mesh geometry={nodes.polySurface10275_dot_4_0.geometry} material={materials.dot_4} />
          <mesh geometry={nodes.polySurface2578_dot_1_0.geometry} material={materials.dot_1} />
          <mesh geometry={nodes.polySurface2399_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface2582_head_2_0.geometry} material={materials.head_2} />
          <mesh geometry={nodes.polySurface10369_armor_4_0.geometry} material={materials.armor_4} />
          <mesh geometry={nodes.polySurface10373_damper_0.geometry} material={materials.damper} />
          <mesh geometry={nodes.polySurface10427_damper3_0.geometry} material={materials.damper3} />
          <mesh geometry={nodes.polySurface10468_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface10469_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface10475_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.polySurface10460_gophra_2_0.geometry} material={materials.gophra_2} />
          <mesh geometry={nodes.polySurface10482_cillinder_0.geometry} material={materials.cillinder} />
          <mesh geometry={nodes.polySurface10515_sphere_0.geometry} material={materials.sphere} />
          <mesh geometry={nodes.polySurface10559_Joint_0.geometry} material={materials.Joint} />
          <mesh geometry={nodes.polySurface10567_ALEX_0.geometry} material={materials.ALEX} />
          <mesh geometry={nodes.polySurface10566_ALEX_0.geometry} material={materials.ALEX} />
          <mesh geometry={nodes.polySurface10565_ALEX_0.geometry} material={materials.ALEX} />
          <mesh geometry={nodes.polySurface10564_ALEX_0.geometry} material={materials.ALEX} />
          <mesh geometry={nodes.polySurface10563_ALEX_0.geometry} material={materials.ALEX} />
          <mesh geometry={nodes.polySurface10562_ALEX_0.geometry} material={materials.ALEX} />
          <mesh geometry={nodes.polySurface10561_ALEX_0.geometry} material={materials.ALEX} />
          <mesh geometry={nodes.polySurface10560_ALEX_0.geometry} material={materials.ALEX} />
          <mesh geometry={nodes.polySurface10497_mount_0.geometry} material={materials.mount} />
          <mesh geometry={nodes.typeMesh4_numbers_0.geometry} material={materials.numbers} />
          <mesh geometry={nodes.pCube342_mirror_1_0.geometry} material={materials.mirror_1} />
          <mesh geometry={nodes.pCube343_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.polySurface10569_Body_0.geometry} material={materials.Body} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/robot.glb')
